Task-5/InventoryManagementSystem/Controllers/DetailsController.cs
using InventoryManagementSystem.Data;
using InventoryManagementSystem.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace InventoryManagementSystem.Controllers
{
    public class DetailsController : Controller
    {
        private readonly ApplicationContext context;

        public DetailsController(ApplicationContext context)
        {
            this.context = context;
        }

        public IActionResult Index()
        {
            var result = context.PurchaseDetails.Include("header").ToList();
            return View(result);
        }



        [HttpGet]
        public IActionResult CreateDetails()
        {

            return View();
        }

       
    }
}

Task-5/InventoryManagementSystem/Controllers/HeaderController.cs
using InventoryManagementSystem.Data;
using InventoryManagementSystem.Models;
using Microsoft.AspNetCore.Mvc;

namespace InventoryManagementSystem.Controllers
{
    public class HeaderController : Controller
    {
        private readonly ApplicationContext context;

        public HeaderController(ApplicationContext context)
        {
            this.context = context;
        }
        public IActionResult Index()
        {
            var result = context.Purchase.ToList();
            return View(result);
        }

   

        

        [HttpGet]
        public IActionResult Purchase() 
        {
        
            return View();
        }

        [HttpPost]
        public IActionResult Purchase(Header name)
        {
            if (ModelState.IsValid)
            {
                var purchase = new Header()
                {
                    PurchaseDate = name.PurchaseDate,
                    SupplierName = name.SupplierName,
                    Address = name.Address,
                    EntryBy = name.EntryBy,
                    EntryDate = name.EntryDate,
                    Remark = name.Remark
                };
                context.Purchase.Add(purchase);
                context.SaveChanges();
                TempData["error"] = "Record Saved!";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["message"] = "Empty field can't submit";
                return View(name);
            }
        }

        public IActionResult Delete(int id)
        {
            var purchase = context.Purchase.SingleOrDefault(u => u.PurchaseId == id);
            context.Purchase.Remove(purchase);
            context.SaveChanges();
            TempData["error"] = "Record Deleted!";
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id) 
        {
            var purchase = context.Purchase.SingleOrDefault(u => u.PurchaseId == id);
            var result = new Header()
            {
                PurchaseDate = purchase.PurchaseDate,
                SupplierName = purchase.SupplierName,
                Address = purchase.Address,
                EntryBy = purchase.EntryBy,
                EntryDate = purchase.EntryDate,
                Remark = purchase.Remark
            };
            return View(result);
        }


        [HttpPost]
        public IActionResult Edit(Header name)
        {
            var Purchase = new Header()
            {
                PurchaseDate = name.PurchaseDate,
                SupplierName = name.SupplierName,
                Address = name.Address,
                EntryBy = name.EntryBy,
                EntryDate = name.EntryDate,
                Remark = name.Remark
            };
            context.Purchase.Update(Purchase);
            context.SaveChanges();
            TempData["error"] = "Record Updated!";
            return RedirectToAction("Index");
        }
    }
}

Task-5/InventoryManagementSystem/Controllers/PurchaseController.cs
using InventoryManagementSystem.Data;
using InventoryManagementSystem.Models;
using Microsoft.AspNetCore.Mvc;

namespace InventoryManagementSystem.Controllers
{
    public class PurchaseController : Controller
    {
        private readonly ApplicationContext context;

        public PurchaseController(ApplicationContext context)
        {
            this.context = context;
        }
        public IActionResult Index()
        {   
            var result = context.PurchaseDetails.ToList();
            return View(result);
        }

        public IActionResult CreatePurchase()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreatePurchase(Detail name)
        {

            var purchase = new Detail()
            {
                PurchaseId = name.PurchaseId,
                ItemCode = name.ItemCode,
                ItemQty = name.ItemQty,
                ItemUnitId = name.ItemUnitId,
                ItemRate = name.ItemRate
            };
            context.PurchaseDetails.Add(purchase);
            context.SaveChanges();
            TempData["error"] = "Record Saved!";
            return RedirectToAction("Index");
            
        }

         public IActionResult Delete(int id)
        {
            var purchase = context.PurchaseDetails.SingleOrDefault(u => u.Id == id);
            context.PurchaseDetails.Remove(purchase);
            context.SaveChanges();
            TempData["error"] = "Record Deleted!";
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id) 
        {
            var purchase = context.PurchaseDetails.SingleOrDefault(u => u.Id == id);
            var result = new Detail()
            {
                PurchaseId = purchase.PurchaseId,
                ItemCode = purchase.ItemCode,
                ItemQty = purchase.ItemQty,
                ItemUnitId = purchase.ItemUnitId,
                ItemRate = purchase.ItemRate
            };
            return View(result);
        }


        [HttpPost]
        public IActionResult Edit(Detail name)
        {
            var Purchase = new Detail()
            {
                PurchaseId = name.PurchaseId,
                ItemCode = name.ItemCode,
                ItemQty = name.ItemQty,
                ItemUnitId = name.ItemUnitId,
                ItemRate = name.ItemRate
            };
            context.PurchaseDetails.Update(Purchase);
            context.SaveChanges();
            TempData["error"] = "Record Updated!";
            return RedirectToAction("Index");
        }
    }
}

Task-5/InventoryManagementSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InventoryManagementSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/InventoryManagementSystem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class=" navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-secondary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Header" asp-action="Index">InventoryManagementSystem</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Header" asp-action="Index">Supplier</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Purchase" asp-action="Index">PurchaseItems</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Details" asp-action="Index">Details</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <span>Md Iqbal Hossain &copy; 2023</span>  <a asp-area="" asp-controller="Header" asp-action="Index">Home</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>